// Illustrative desktop drawn at the screen's effective resolution, then scaled down.
// More effective pixels means more of this fits, which is the point of the preview.
// Static markup with no user data. Ported from the original page.

let cached: string | null = null;

export function workPreviewMarkup(): string {
  if (cached) return cached;
  cached = build();
  return cached;
}

function build(): string {
        const bar = (title: string, colour: string) => `<div class="sim-work-windowbar"><i style="background:${colour}"></i>${title}<span class="sim-work-window-actions">− &nbsp; □ &nbsp; ×</span></div>`;
        const lines = (count: number) => Array.from({ length: count }, (_, i) => `<div class="sim-work-line" style="width:${[96, 88, 100, 73, 92, 61][i % 6]}%"></div>`).join('');
        const rows = Array.from({ length: 55 }, (_, i) => `<tr><td>${i + 1}</td><td>${['Website refresh', 'Customer research', 'Launch campaign', 'Product photography', 'Support centre', 'Quarterly review'][i % 6]}</td><td>${['Alex', 'Sam', 'Jamie', 'Morgan'][i % 4]}</td><td><span class="sim-work-status">${['In progress', 'Approved', 'Review'][i % 3]}</span></td><td>${12 + i} Sep</td><td>£${(240 + i * 85).toLocaleString('en-GB')}</td></tr>`).join('');
        const messages = Array.from({ length: 24 }, (_, i) => `<div class="sim-work-message"><b style="background:${['#e8e6fd', '#def0ec', '#fff0db'][i % 3]}">${['AL', 'SK', 'JM'][i % 3]}</b><div><strong>${['Alex Lee', 'Sam Kim', 'Jamie Moss'][i % 3]} <small>${9 + Math.floor(i / 6)}:${String(i % 6 * 10).padStart(2, '0')}</small></strong><p>${['The updated designs are ready for review.', 'Looks good. I’ve added the latest figures.', 'Let’s cover the final details in our catch-up.', 'Shared the project notes with the team.'][i % 4]}</p></div></div>`).join('');
        return `<div class="sim-work sim-work-full">
      <div class="sim-work-topbar"><span class="sim-work-brand">Workspace</span><span class="sim-work-search">Search files, messages and projects</span><span class="sim-work-clock">09:41 &nbsp; · &nbsp; Friday</span></div>
      <div class="sim-work-desktop">
        <section class="sim-work-window">${bar('Project notes · Launch plan', '#8b82ed')}<div class="sim-work-docbody"><aside class="sim-work-nav"><strong>PROJECTS</strong><span></span><span></span><span></span><span></span><strong>DOCUMENTS</strong><span></span><span></span></aside><div class="sim-work-page"><small>TEAM SPACE / PLANNING</small><h4>Making room for what’s next</h4><p class="sim-work-subtitle">Quarterly plan · Updated today</p><div class="sim-work-callout">Our focus: a simpler experience, a stronger launch.</div>${Array.from({ length: 8 }, (_, i) => `<h5>${['01 — Overview', '02 — Goals & priorities', '03 — Research findings', '04 — Design direction', '05 — Delivery plan', '06 — Success measures', '07 — Next steps', '08 — Meeting notes'][i]}</h5>${lines(8)}`).join('')}</div></div></section>
        <section class="sim-work-window">${bar('Analytics · Performance overview', '#6e92df')}<div class="sim-work-dashboard"><div class="sim-work-dashboard-heading"><h4>Performance overview</h4><span>Last 30 days ▾</span></div><div class="sim-work-metrics"><div class="sim-work-metric"><small>Revenue</small><strong>£84,240</strong><em>↑ 12.8%</em></div><div class="sim-work-metric"><small>Orders</small><strong>1,248</strong><em>↑ 8.2%</em></div><div class="sim-work-metric"><small>Conversion</small><strong>3.6%</strong><em>↑ 0.4%</em></div></div><div class="sim-work-chart">${Array.from({ length: 12 }, (_, i) => `<span style="height:${[32, 46, 40, 63, 51, 72, 58, 76, 68, 83, 75, 92][i]}%"></span>`).join('')}</div><div class="sim-work-chart-labels"><span>Week 1</span><span>Week 2</span><span>Week 3</span><span>Week 4</span></div><h5>Channel breakdown</h5>${Array.from({ length: 20 }, (_, i) => `<div class="sim-work-channel"><span>${['Organic search', 'Direct traffic', 'Email campaigns', 'Social media', 'Referrals'][i % 5]}</span><div><i style="width:${[82, 65, 49, 38, 25][i % 5]}%"></i></div><strong>${[42, 28, 16, 9, 5][i % 5]}%</strong></div>`).join('')}</div></section>
        <section class="sim-work-window">${bar('Project tracker.xlsx', '#489885')}<div class="sim-work-sheet-toolbar">File &nbsp; Home &nbsp; Insert &nbsp; Data &nbsp; View <span>All changes saved</span></div><div class="sim-work-formula">D4 &nbsp; │ &nbsp; ƒx &nbsp; Launch campaign</div><table class="sim-work-sheet"><thead><tr><th>#</th><th>Project</th><th>Owner</th><th>Status</th><th>Due</th><th>Budget</th></tr></thead><tbody>${rows}</tbody></table></section>
        <section class="sim-work-window">${bar('Team chat & today’s agenda', '#dfaa65')}<div class="sim-work-collaboration"><div class="sim-work-conversation"><div class="sim-work-chat-heading"># launch-team <small>8 members · 3 online</small></div>${messages}</div><aside class="sim-work-agenda"><h5>Friday, 18</h5><p>Today’s schedule</p>${Array.from({ length: 14 }, (_, i) => `<div class="sim-work-event"><small>${String(9 + Math.floor(i / 2)).padStart(2, '0')}:${i % 2 ? '30' : '00'}</small><strong>${['Team catch-up', 'Design review', 'Focus time', 'Launch planning'][i % 4]}</strong><span>${['Meeting room 2', 'Video call', 'No interruptions', 'Project team'][i % 4]}</span></div>`).join('')}</aside></div></section>
      </div><div class="sim-work-taskbar"><b>▦</b><span class="sim-work-task-icon">W</span><span class="sim-work-task-icon">X</span><span class="sim-work-task-icon">◉</span><span class="sim-work-task-icon">✉</span><span>● &nbsp; All files up to date</span></div>
    </div>`;
    }
